sudo: true
language: node_js
node_js:
  - '10'
branches:
  except:
    - /^v\d+\.\d+\.\d+.*/
    - gh-pages
after_success:
  if ([ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]); then
    eval 'npm run semantic-release';
  fi
